name: Publish to Tencent Cloud COS
description: Publish static files to Tencent Cloud Object Storage

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install coscmd
      run: pip install coscmd
      shell: bash

    - name: Configure coscmd
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b nk2028-1305783649 -r ap-guangzhou
      shell: bash

    - name: Publish static files to COS
      run: coscmd upload -rs --delete -f . /tshet-uinh-examples --ignore '*/.*,*/node_modules/*,./test/*,./build/*,./dist/*,./package.json,./package-lock.json,./eslint.config.js'
      shell: bash
